set dotenv-load

pwd := `pwd`
vcpkg_installed := pwd + '/vcpkg_installed/x64-linux'

run: build
    build/womf

gdb: build
    gdb build/womf

setup build_dir='build/':
    meson setup \
        "-Dpkg_config_path={{vcpkg_installed}}/lib/pkgconfig/:{{vcpkg_installed}}/share/pkgconfig" \
        "-Dincludedir={{vcpkg_installed}}/include/" \
        "{{build_dir}}"

build build_dir='build/':
    meson compile -C "{{build_dir}}"

vcpkg-install:
    vcpkg install

# The clang-tidy build target is generated by meson
check build_dir='build/':
    ninja -C {{build_dir}} clang-tidy
